schema-version: v2
kind: plugin
metadata:
  name: gha-stk-self-hosted
  display-name: gha-stk-self-hosted
  description: Plugin to add a StackSpot Self Hosted Runtime GitHub actions workflow
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  repository: https://github.com/GuillaumeFalourd/stackspot-plugins
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Github Actions
  inputs:
    - label: Self Hosted Runner name
      name: self_hosted_runner_name
      type: text
      required: true
      default: ubuntu-latest
      help: 'Self Hosted Runner used to execute the repository workflow on Github Actions'
    - label: Workspace where the project will be deployed
      name: workspace
      type: text
      required: true
      help: 'Inform the StackSpot Workspace name where the application has been registered'
    - label: Environment where the project will be deployed
      name: environment
      type: text
      required: true
      help: 'Inform the StackSpot Environment name where the application will be deployed'
    - label: TFState Bucket Name
      name: tfstate_bucket_name
      type: text
      required: true
      help: 'S3 bucket name where the tfstate files generated during the process will be stored'
    - label: IAC Bucket Name
      name: iac_bucket_name
      type: text
      required: true
      help: 'S3 bucket name where the IaC files generated during the process will be stored'
    - label: AWS region
      name: aws_region
      type: text
      required: true
      default: us-east-1
      help: 'AWS Region where the resources will be provisioned and stores (e.g: us-east-1)'
    - label: Github repository name
      name: github_repository_name
      type: text
      required: true
      help: 'Github repository name'