schema-version: v1
kind: plugin
metadata:
  name: issues-templates
  display-name: issues-templates
  description: Plugin to add issue templates to the GitHub repository
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
    - GitHub